redirect_uri = "https://mag4datasharing-app-pb0ioldt9x.streamlit.app/Orcid_test"
cookie_secret = "96cf081a-61c1-b22e-f644-6eaa1ab31cc0"
client_id = "APP-5JWQJHNH88OKN8AN"
client_secret = "cf36517f-e6a2-41e4-83b0-5a2d443d5741"
server_metadata_url = "https://orcid.org/.well-known/openid-configuration"